spring.application.name=ms-seguridad
#PATH por default apra toda nuestras apis del msv
server.servlet.context-path=/apis/codigo
spring.datasource.url=jdbc:postgresql://localhost:5432/bdsecurityg9
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
dato.propiedad=Hola Mundo 2
logging.level.root=debug
key.signature=hHRh+AxE3keAHC0UTTg/PdkT1bNzu4/Foa8QGoRDtZgn1eAe1V8J1zLflgOGY9/PVF1Lpmg7jy9ScmECOGZtiA==



